### ISSUE TITLE
Support type hinting

### ISSUE THREAD

**Issue by q-wertz** [python-visualization/folium#1559]
**Is your feature request related to a problem? Please describe.**
Currently type hinting is not supported by folium. Are there any plans to implement this?

**Describe the solution you'd like**
Typing in folium and type hints for the public interfaces (Maybe [autogenerated](https://mypy.readthedocs.io/en/stable/stubgen.html))

**Describe alternatives you've considered**
Excluding folium in my personal project from type checking by mypy

**Additional context**
None

**Implementation**
folium is maintained by volunteers. Can you help make a PR if we want to implement this feature?
-> Can try to help with this

**Comment by Conengmo** [comment]
Yes, that would be nice. Though type hints in folium are not that useful, since we use a lot of duck-typing. I was working on a change a while back: https://github.com/python-visualization/folium/pull/1297/

**Comment by q-wertz** [comment]
Ah sorry, didn't see the PR only searched the issues.

Is it not merged due to a certain reason or just not finished?

**Comment by q-wertz** [comment]
If you need testing or something I can help with let me know

**Comment by q-wertz** [comment]
After updating folium to 0.15.0 mypy still says:
```
plots.py:11: error: Skipping analyzing "folium": module is installed, but missing library stubs or py.typed marker  [import-untyped]
plots.py:11: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

Not a pro in this, but I think you need to add an (empty) `py.typed` file in the `folium` folder. (At least mypy stops giving the error message as soon as I add it manually in my venv folium lib...
